### ISSUE TITLE
Tool for breast cancer detection

### ISSUE THREAD

**Issue by rajat1994** [aditisingh/Breast_cancer_detection#1]
I think a diagnostic tool would be better so that doctors can use it. I am also working on a breast cancer project. This is the repo link : https://github.com/rajat1994/WebApp-for-breast-cancer-detection
Link of the tool (web app) : https://warm-falls-58774.herokuapp.com/

**Comment by aditisingh** [comment]
I am working on something similar, in my case the input is images, instead of features.

**Comment by TanPhuNguyen** [comment]
@aditisingh You used Ubuntu operating system for making this repo, right??

**Comment by TanPhuNguyen** [comment]
@rajat1994 thank you for your repo, Can I exchange with you if I have the questions related to your repo?
thank you in advance!
