### ISSUE TITLE
ValueError: Cannot feed value of shape (33, 4096) for Tensor 'InputData/X:0', which has shape '(?, 227, 227, 3)'

### ISSUE THREAD

**Issue by greatpak** [aditisingh/Breast_cancer_detection#2]
Dear Aditisingh
ValueError: Cannot feed value of shape (33, 4096) for Tensor 'InputData/X:0', which has shape '(?, 227, 227, 3)'

Please help me.

Thank You

**Comment by aditisingh** [comment]
What code are you using?

**Comment by greatpak** [comment]
Dear Aditisingh,
Thank You for your reply.
First I run the vgg16_cv.py, second generate_features.py , Third data_load and four alexnet.py is running. The error comes **ValueError: Found input variables with inconsistent numbers of samples: [1, 49]** . Please help me.

**Comment by aditisingh** [comment]
What is the size of your input data X?

**Comment by greatpak** [comment]
>>> X.size
5206016
>>> X.shape
(1271, 4096)

**Comment by aditisingh** [comment]
There is a bug in alexnet.py. It should use the original image (resized to 227x227x3) instead of the features extracted from VGG16. Try that. I will update it soon.
